### PR TITLE
Fix NaN issues when compressing zeros

### LINKED ISSUE #21: Dysco changes full zero input to NaNs
In some of Emilio's imaging, we noticed that if we do a Stokes I DP3 prediction into a Dysco-d set, the XY / YX polarizations become NaN values. While Dysco shouldn't be used in such cases (noiseless data), it's likely that it occasionally is done by astronomers, and in most cases, applying Dysco on a noise-less column won't hurt much (it just adds a bit of noise). Therefore, it is probably desirable to fix this issue and make Dysco work on all-zero data.

It's likely that the normalization of the data by its variance at some point causes a division by zero inside Dysco, causing NaNs. The compression algorithm is a separate class that's not dependent on measurement sets so this issue should easily be unit-testable.

While NaNs in the XY/YX polarizations shouldn't really be a problem, it turned out that this triggered another interesting bug inside WSClean when using IDG. For IDG, all polarizations are used, so those NaNs are fed to IDG, even when imaging Stokes I. It seems that the normalization of the image in this case no longer works: the dirty image produced by wsclean+IDG contains values which are 5-6 order of magnitude too large, and because of this, the prediction cycle diverges. I don't know if that is happening inside wsclean or IDG.

### PR DESCRIPTION
**Pull request by aroffringa**
Once finished, this Fixes #21.

### CODE REVIEW

**Comment by tammojan** [comment]
I see only changes to a test file. Could it be that you forgot to check something in?

**Comment by aroffringa** [comment]
I'm not done yet ;). The test reproduces the problem though.

**Comment by aroffringa** [comment]
The source isn't formatted -- running the format script caused lots of more changes, so apparently the master wasn't formatted yet (I introduced the formatting script for the transfer of Dysco to Casacore). I'll do formatting in a separate MR to keep this MR somewhat clean.

**Comment by tammojan** [comment]
Looks good to me!

**Pull request merged**
